<% credentials = Rails.application.credentials.twilio %>

shared:
  account_sid: <%= credentials.account_sid %>
  auth_token: <%= credentials.auth_token %>
  phone_number: <%= credentials.phone_number %>
  url_base: https://api.twilio.com
